#ifndef RPI_DRIVER_MUSICBOX_H
#define RPI_DRIVER_MUSICBOX_H

typedef enum {
  MUSICBOX_SET_VOLUMN,
  MUSICBOX_GET_VOLUMN,
  MUSICBOX_SET_BEAT,
  MUSICBOX_GET_BEAT,
} musicbox_cmd_t;

#endif // !RPI_DRIVER_MUSICBOX_H