#ifndef RPI_DRIVER_INACTION_PWMLED_H
#define RPI_DRIVER_INACTION_PWMLED_H

// PWM输出的频率为 1k Hz
#define PWMLED_MAX_BRIGHTNESS 1000

typedef enum {
  PWMLED_CMD_SET_BRIGHTNESS = 0x1,
  PWMLED_CMD_GET_BRIGHTNESS,
} pwmled_cmd_t;

#endif // !RPI_DRIVER_INACTION_PWMLED_H